// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SetConfigRequest 设置配置请求
type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_api_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *SetConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SetConfigResponse 设置配置响应
type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_api_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *SetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetConfigRequest 获取配置请求
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetConfigResponse 获取配置响应
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigItem            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigResponse) GetConfig() *ConfigItem {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// GetServiceConfigsRequest 获取服务配置请求
type GetServiceConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigsRequest) Reset() {
	*x = GetServiceConfigsRequest{}
	mi := &file_api_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigsRequest) ProtoMessage() {}

func (x *GetServiceConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceConfigsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// GetServiceConfigsResponse 获取服务配置响应
type GetServiceConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*ConfigItem `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceConfigsResponse) Reset() {
	*x = GetServiceConfigsResponse{}
	mi := &file_api_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigsResponse) ProtoMessage() {}

func (x *GetServiceConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceConfigsResponse) GetConfigs() map[string]*ConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

// DeleteConfigRequest 删除配置请求
type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_api_proto_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeleteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteConfigResponse 删除配置响应
type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_api_proto_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteServiceConfigsRequest 删除服务配置请求
type DeleteServiceConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceConfigsRequest) Reset() {
	*x = DeleteServiceConfigsRequest{}
	mi := &file_api_proto_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceConfigsRequest) ProtoMessage() {}

func (x *DeleteServiceConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceConfigsRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteServiceConfigsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// DeleteServiceConfigsResponse 删除服务配置响应
type DeleteServiceConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceConfigsResponse) Reset() {
	*x = DeleteServiceConfigsResponse{}
	mi := &file_api_proto_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceConfigsResponse) ProtoMessage() {}

func (x *DeleteServiceConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceConfigsResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServiceConfigsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteServiceConfigsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListServicesRequest 列出服务请求
type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_api_proto_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{10}
}

// ListServicesResponse 列出服务响应
type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_api_proto_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{11}
}

func (x *ListServicesResponse) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

// WatchConfigRequest 监听配置请求
type WatchConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // 可选，如果为空则监听整个服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigRequest) Reset() {
	*x = WatchConfigRequest{}
	mi := &file_api_proto_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigRequest) ProtoMessage() {}

func (x *WatchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{12}
}

func (x *WatchConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *WatchConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// WatchConfigResponse 监听配置响应
type WatchConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // PUT, DELETE
	Config        *ConfigItem            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigResponse) Reset() {
	*x = WatchConfigResponse{}
	mi := &file_api_proto_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigResponse) ProtoMessage() {}

func (x *WatchConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigResponse.ProtoReflect.Descriptor instead.
func (*WatchConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{13}
}

func (x *WatchConfigResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WatchConfigResponse) GetConfig() *ConfigItem {
	if x != nil {
		return x.Config
	}
	return nil
}

// ConfigItem 配置项
type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_api_proto_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ConfigItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ConfigItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_api_proto_config_proto protoreflect.FileDescriptor

const file_api_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/config.proto\x12\x06config\"\x7f\n" +
	"\x10SetConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"G\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x10GetConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"U\n" +
	"\x11GetConfigResponse\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x12.config.ConfigItemR\x06config\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"=\n" +
	"\x18GetServiceConfigsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xb5\x01\n" +
	"\x19GetServiceConfigsResponse\x12H\n" +
	"\aconfigs\x18\x01 \x03(\v2..config.GetServiceConfigsResponse.ConfigsEntryR\aconfigs\x1aN\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.config.ConfigItemR\x05value:\x028\x01\"J\n" +
	"\x13DeleteConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"J\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x1bDeleteServiceConfigsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"R\n" +
	"\x1cDeleteServiceConfigsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13ListServicesRequest\"2\n" +
	"\x14ListServicesResponse\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\"I\n" +
	"\x12WatchConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"`\n" +
	"\x13WatchConfigResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12*\n" +
	"\x06config\x18\x02 \x01(\v2\x12.config.ConfigItemR\x06config\"\xb7\x01\n" +
	"\n" +
	"ConfigItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt2\xb0\x04\n" +
	"\rConfigService\x12@\n" +
	"\tSetConfig\x12\x18.config.SetConfigRequest\x1a\x19.config.SetConfigResponse\x12@\n" +
	"\tGetConfig\x12\x18.config.GetConfigRequest\x1a\x19.config.GetConfigResponse\x12X\n" +
	"\x11GetServiceConfigs\x12 .config.GetServiceConfigsRequest\x1a!.config.GetServiceConfigsResponse\x12I\n" +
	"\fDeleteConfig\x12\x1b.config.DeleteConfigRequest\x1a\x1c.config.DeleteConfigResponse\x12a\n" +
	"\x14DeleteServiceConfigs\x12#.config.DeleteServiceConfigsRequest\x1a$.config.DeleteServiceConfigsResponse\x12I\n" +
	"\fListServices\x12\x1b.config.ListServicesRequest\x1a\x1c.config.ListServicesResponse\x12H\n" +
	"\vWatchConfig\x12\x1a.config.WatchConfigRequest\x1a\x1b.config.WatchConfigResponse0\x01B\x1dZ\x1bnidavellir/api/proto/configb\x06proto3"

var (
	file_api_proto_config_proto_rawDescOnce sync.Once
	file_api_proto_config_proto_rawDescData []byte
)

func file_api_proto_config_proto_rawDescGZIP() []byte {
	file_api_proto_config_proto_rawDescOnce.Do(func() {
		file_api_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_config_proto_rawDesc), len(file_api_proto_config_proto_rawDesc)))
	})
	return file_api_proto_config_proto_rawDescData
}

var file_api_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_config_proto_goTypes = []any{
	(*SetConfigRequest)(nil),             // 0: config.SetConfigRequest
	(*SetConfigResponse)(nil),            // 1: config.SetConfigResponse
	(*GetConfigRequest)(nil),             // 2: config.GetConfigRequest
	(*GetConfigResponse)(nil),            // 3: config.GetConfigResponse
	(*GetServiceConfigsRequest)(nil),     // 4: config.GetServiceConfigsRequest
	(*GetServiceConfigsResponse)(nil),    // 5: config.GetServiceConfigsResponse
	(*DeleteConfigRequest)(nil),          // 6: config.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),         // 7: config.DeleteConfigResponse
	(*DeleteServiceConfigsRequest)(nil),  // 8: config.DeleteServiceConfigsRequest
	(*DeleteServiceConfigsResponse)(nil), // 9: config.DeleteServiceConfigsResponse
	(*ListServicesRequest)(nil),          // 10: config.ListServicesRequest
	(*ListServicesResponse)(nil),         // 11: config.ListServicesResponse
	(*WatchConfigRequest)(nil),           // 12: config.WatchConfigRequest
	(*WatchConfigResponse)(nil),          // 13: config.WatchConfigResponse
	(*ConfigItem)(nil),                   // 14: config.ConfigItem
	nil,                                  // 15: config.GetServiceConfigsResponse.ConfigsEntry
}
var file_api_proto_config_proto_depIdxs = []int32{
	14, // 0: config.GetConfigResponse.config:type_name -> config.ConfigItem
	15, // 1: config.GetServiceConfigsResponse.configs:type_name -> config.GetServiceConfigsResponse.ConfigsEntry
	14, // 2: config.WatchConfigResponse.config:type_name -> config.ConfigItem
	14, // 3: config.GetServiceConfigsResponse.ConfigsEntry.value:type_name -> config.ConfigItem
	0,  // 4: config.ConfigService.SetConfig:input_type -> config.SetConfigRequest
	2,  // 5: config.ConfigService.GetConfig:input_type -> config.GetConfigRequest
	4,  // 6: config.ConfigService.GetServiceConfigs:input_type -> config.GetServiceConfigsRequest
	6,  // 7: config.ConfigService.DeleteConfig:input_type -> config.DeleteConfigRequest
	8,  // 8: config.ConfigService.DeleteServiceConfigs:input_type -> config.DeleteServiceConfigsRequest
	10, // 9: config.ConfigService.ListServices:input_type -> config.ListServicesRequest
	12, // 10: config.ConfigService.WatchConfig:input_type -> config.WatchConfigRequest
	1,  // 11: config.ConfigService.SetConfig:output_type -> config.SetConfigResponse
	3,  // 12: config.ConfigService.GetConfig:output_type -> config.GetConfigResponse
	5,  // 13: config.ConfigService.GetServiceConfigs:output_type -> config.GetServiceConfigsResponse
	7,  // 14: config.ConfigService.DeleteConfig:output_type -> config.DeleteConfigResponse
	9,  // 15: config.ConfigService.DeleteServiceConfigs:output_type -> config.DeleteServiceConfigsResponse
	11, // 16: config.ConfigService.ListServices:output_type -> config.ListServicesResponse
	13, // 17: config.ConfigService.WatchConfig:output_type -> config.WatchConfigResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_config_proto_init() }
func file_api_proto_config_proto_init() {
	if File_api_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_config_proto_rawDesc), len(file_api_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_config_proto_goTypes,
		DependencyIndexes: file_api_proto_config_proto_depIdxs,
		MessageInfos:      file_api_proto_config_proto_msgTypes,
	}.Build()
	File_api_proto_config_proto = out.File
	file_api_proto_config_proto_goTypes = nil
	file_api_proto_config_proto_depIdxs = nil
}
