# Nidavellir 配置中心配置文件

# HTTP服务器配置
[http]
host = "127.0.0.1"
port = 9990
enable = false

# gRPC服务器配置
[grpc]
host = "127.0.0.1"
port = 9991
enable = false

# twig配置
[twig]
address = "/var/run/Nidavellir.sock"
enable = true

# etcd配置
[etcd]
endpoints = ["localhost:2379"]
dial_timeout = 5
username = ""
password = ""

# 日志配置
[log]
level = "info"
format = "json"